version: '3'

services:
  ascalongw:
    build: .
    environment:
      ASCALONGW_PREFIX: ${ASCALONGW_PREFIX}
      ASCALONGW_OWNERS: ${ASCALONGW_OWNERS}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 60s
      retries: 5
      start_period: 30s
      timeout: 10s
