{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"discord-bot\"}[7d]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total servers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(discord_guild_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(discord_guild_members)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Interactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(bot_command_count)", "legendFormat": "Commands" },
    { "expr": "sum(bot_button_count)", "legendFormat": "Buttons" },
    { "expr": "sum(bot_autocomplete)", "legendFormat": "Autocompletions" }
   ]
  },
  {
   "title": "Command Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "bot_command_count{type=\"slash\"}",
     "legendFormat": "/{{command}} {{subcommand_group}} {{subcommand}}"
    },
    {
     "expr": "bot_command_count{type=\"message\"}",
     "legendFormat": "@{{command}} {{subcommand_group}} {{subcommand}}"
    }
   ]
  },
  {
   "title": "Button Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "targets": [
    { "expr": "bot_button_count", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Autocompletion Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "bot_autocomplete",
     "legendFormat": "/{{command}} {{subcommand_command}} {{subcommand}} [{{option}}]"
    }
   ]
  },
  {
   "title": "Command Usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bot_command_count{type=\"slash\"}",
     "legendFormat": "/{{command}} {{subcommand_group}} {{subcommand}}"
    },
    {
     "expr": "bot_command_count{type=\"message\"}",
     "legendFormat": "@{{command}} {{subcommand_group}} {{subcommand}}"
    }
   ]
  },
  {
   "title": "Button Usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bot_button_count", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Command Usage by type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bot_command_count{type=\"slash\"})",
     "legendFormat": "Slash"
    },
    {
     "expr": "sum(bot_command_count{type=\"message\"})",
     "legendFormat": "Message"
    }
   ]
  },
  {
   "title": "User Count by Server",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "discord_guild_members * on(guild) group_left(name) discord_guild_info",
     "legendFormat": "{{name}}"
    },
    {}
   ]
  }
 ]
}